### ISSUE TITLE
Crash and Error

### ISSUE THREAD

**Issue by Turi-Nord** [stride3d/stride#2192] opened 2024-03-20 08:51 UTC
**Version**: 4.0.2121

**Platform(s)**: Win 10
The Program crash back to Windows after clicking on Settings. The Editor show many errors.
Send an Error is not possible because all crash.

**To Reproduce**
Open the Example (CSharpbeginner), doubleclick on a script, Editor opened with Errors, click on Settings

Open the Scripts in Visual Studio is working fine.
![Stride Bug](https://github.com/stride3d/stride/assets/164153620/1473712c-0830-4b7b-b327-16bb7e790a9d)
![Stride Bug 2](https://github.com/stride3d/stride/assets/164153620/ced326be-cc6a-441e-9251-2340df332c91)

**Comment by Doprez** [comment] 2024-03-21 17:23
Hello, there seems to be an issue with some changes to the settings window in version 4.2.2121. If you switch to version 4.2.2067 you should not have the same issue. https://github.com/stride3d/stride/issues/2194#issuecomment-2013115336

**Comment by Eideren** [comment] 2024-03-23 17:23
Should be fixed, update to 4.2.0.2122 through the launcher.

**Comment by Eideren** [comment] 2024-03-23 17:26
Actually, I'll just close this one since it's a duplicate of #2182 - feel free to continue the conversation over there instead

**Closed by Eideren** 2024-03-23 17:26 UTC
Labels: bug
