### ISSUE TITLE
Xenko does not work without the Internet.

### ISSUE THREAD

**Issue by Degaron** [stride3d/stride#282] opened 2018-12-02 12:07 UTC
Xenko does not work without the Internet.

https://pastebin.com/ZW5kmx5b

**Comment by Degaron** [comment] 2018-12-02 12:31
Xenko not starting.
I deleted Xenko.

**Comment by tebjan** [comment] 2018-12-02 13:05
hi @Degaron, the installer needs to download packages from the xenko server in order to install it. its an online installer.
i think the issue with internet connection on startup is already fixed for 3.0.0.7. see https://github.com/xenko3d/xenko/commit/d17e74d6619835219b06776258089af02a1a22fb

**Comment by Degaron** [comment] 2018-12-02 15:05
I downloaded the packages.

**Comment by tebjan** [comment] 2018-12-02 15:17
how did you download them? via the installer?

**Comment by Kryptos-FR** [comment] 2018-12-03 07:59
@Degaron The installer from the download page is a light-weight installer that will just install the Xenko launcher. Similarly to what Microsoft does with Visual Studio 2017. Then it needs to get the newest package from the server. So indeed you do need a working Internet connection to install it and also to get updates.

Note that the initial installer also needs an Internet connection to get the prerequisites packages (.Net SDK, MSBuild, etc.).

@xen2 Maybe we should make it more obvious in the download page that a connection is required. I was also wondering whether we could provide an offline package (i.e. launcher+latest version) but I don't think we can include the third-party dependencies (such as MSBuild) without license issues.

**Comment by Degaron** [comment] 2018-12-03 22:40
You probably did not understand.
The first post is exactly what you are talking about.
But after that, I installed Xenko and got a lot of errors when trying to run Xenko.

**Comment by Kryptos-FR** [comment] 2018-12-04 00:05
Sorry can't read pastebin links. Write relevant information here (maybe not the full log but at least the relevant error message).

Secondly, the title of the issue is "Xenko does not work without the Internet" so I am answering that.

**Comment by Eideren** [comment] 2020-04-28 18:33
#399 covers this issue, closing this one.

**Closed by Eideren** 2020-04-28 18:33 UTC
