### ISSUE TITLE
Error:An exception occurred while generating the template.

### ISSUE THREAD

**Issue by Stefos-art** [stride3d/stride#625] opened 2020-03-15 09:21 UTC
Version 3.1.0.1
Project Selection screen:
New Project:
New Game: Error:An exception occurred while generating the template.
New Project:
Template: First Person Shooter: Error:An exception occurred while generating the template.

I think you get the drift....nothing works!

**Comment by Kryptos-FR** [comment] 2020-03-15 11:13
We are going more details than that. If I follow the same steps on my machine it works fine.

You are most likely missing some prerequisites/dependencies. Or there could be some trouble with nuget/internet and it fails to download the required packages.

**Comment by Stefos-art** [comment] 2020-03-15 13:21
Thanks for that, so what should I do? can I download the nuget packages manually? how can I find out what is missing?

**Comment by xen2** [comment] 2020-03-15 13:42
You can press the small icons with `...` (3 dots) to have more details

**Comment by Stefos-art** [comment] 2020-03-15 14:16
![Screenshot_9](https://user-images.githubusercontent.com/62201786/76703166-4718d400-66d8-11ea-8189-6c7c051ca3bb.jpg)

**Comment by Stefos-art** [comment] 2020-03-15 14:16
Please let me know where these dots are?

**Comment by Stefos-art** [comment] 2020-03-15 14:18
Error:An exception occurred while generating the template.
The SDK 'Microsoft.NET.Sdk' specified could not be found.  c:\Users\Stefos\Documents\Xenko Projects\FirstPersonShooter5\FirstPersonShooter5.Game\FirstPersonShooter5.Game.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Xenko.Core.Assets.VSProjectHelper.LoadProject(String fullProjectLocation, String configuration, String platform, Dictionary`2 extraProperties)
   at Xenko.Assets.Presentation.Templates.TemplateSampleGenerator.Generate(SessionTemplateGeneratorParameters parameters)
   at Xenko.Core.Assets.Editor.Components.TemplateDescriptions.SessionTemplateGenerator.Run(SessionTemplateGeneratorParameters parameters)
   at Xenko.Core.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0()

**Comment by Stefos-art** [comment] 2020-03-15 14:18
I am guessing by this there is a problem with Microsoft.NET.Sdk?

**Comment by Eideren** [comment] 2020-04-27 18:06
Duplicate of #673 , I'll close this one off even if it is technically older than that one

**Closed by Eideren** 2020-04-27 18:06 UTC
Labels: bug
