### ISSUE TITLE
First Person Shooter example fails at running.

### ISSUE THREAD

**Issue by meriaizen86** [stride3d/stride#585] opened 2020-01-29 18:10 UTC
**Xenko Release**: 3.1.0.1 

**Platform(s)**: Windows 10

**Setup**

-Windows 10 Pro 1909-18363.592

-Ryzen 5 2600

-Gygabyte AMD Radeon Series RX 580 GV-R850GAMING-8GD

-AMD Gfx drivers version: 20.1.4-jan27

**Describe the bug**
Game template builds succesfully, but fails at run returning an error "Unexpected exception while loading asset [GameSettings]. Reason: No serializer available for type id f6e78a35184f6fe1d27096e38ec09340 and base type Xenko.Data.Configuration. Check inner-exception for details"

**To Reproduce**

1.  Create a new First Person Shooter from template.

2. Edit the game settings and set the graphics manager to DirectX 11, change resolution to 1920x1080 and check "adapt backbuffer to screen" option.
![imagen](https://user-images.githubusercontent.com/26027169/73383869-6e534780-42ca-11ea-84e0-980e71e05241.png)

3. Click on build and run button. 

**Expected behavior**

Game ready to testing and running.

**Log and callstacks**

[FirstPerson.txt](https://github.com/xenko3d/xenko/files/4129705/FirstPerson.txt)

**Additional context**

**Comment by meriaizen86** [comment] 2020-02-02 17:48
Same error happens on Xenko GameStudio 3.2.0.1-beta2-

**Comment by Basewq** [comment] 2020-02-02 22:51
The issue isn't specifically related to the graphics settings.
See #580 where what is actually happening is the `NavigationSettings` is being restored on the `GameSettings` asset, and this causes it to fail to load.

**Comment by meriaizen86** [comment] 2020-02-03 22:43
Thank you so much!

**Comment by meriaizen86** [comment] 2020-02-03 22:45
So I leave this issue open or we can close it?

**Comment by Eideren** [comment] 2020-04-27 18:42
Duplicate of #580

**Closed by Eideren** 2020-04-27 18:42 UTC
Labels: bug
