### ISSUE TITLE
Could not find a compatible version of MSBuild.

### ISSUE THREAD

**Issue by DIMANRUS** [stride3d/stride#1630] opened 2023-03-14 09:05 UTC
**Release Type**: Official Release/GitHub (please choose appropriate option)
Official Release
**Version**: Version number and/or git branch
4.1.0.1805
**Platform(s)**: Does the problem occur on Windows, Android...?
Windows
**Describe the bug**
When creating a project, after restoring NuGet packages, it cannot find a suitable version of MSBuild. Visual Studio 2022 Enterprise 17.5.1 with MSBuild 17.5.0.10706 is installed on the computer, but in addition to the 2022 version, I still have 2017 and 2015 versions of visual studio. I assume he is looking for it from them, not in the 2022 version.

**To Reproduce**
1. Install Visual Studio 2022,2017,2015
2. Open Stride Launcher
3. Click Start
4. Error

**Expected behavior**
Project templates will appear and I will be able to create it

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)
![image](https://user-images.githubusercontent.com/41239551/224949862-bdd0885a-950e-4021-918d-e0e1efce5371.png)
![image](https://user-images.githubusercontent.com/41239551/224949961-b2c4af8a-e109-4613-a054-ba964aecba36.png)

**Additional context**
[Visual Studio 2017 Link](https://disk.yandex.ru/d/U6bsxMD1gEYcvQ)
[Visual Studio 2015 Link](https://disk.yandex.ru/d/HfUwyhWpPJt98A)

**Comment by manio143** [comment] 2023-03-14 11:52
Duplicate of #756
At the moment you need to have the correct SDK version installed - for Stride 4.1 that's .net 6 SDK. Visual Studio by default installs the latest which is .net 7 - while a newer SDK can compile project targeting older runtime, Stride integrates with MSBuild and requires a specific SDK version to be installed.

**Comment by DIMANRUS** [comment] 2023-03-14 12:19
Thank you.🙂

**Closed** 2023-03-14 12:19 UTC
Labels: bug
