### ISSUE TITLE
[Prereq] Error code 1

### ISSUE THREAD

**Issue by Alanjdv** [stride3d/stride#665] opened 2020-04-23 09:48 UTC
**Release Type**: Official Release/GitHub (please choose appropriate option)
Release
**Version**: Version number and/or git branch
3.1.0.1
**Platform(s)**: Does the problem occur on Windows, Android...?
Windows 10, 64
**Describe the bug**
Cannot install Stride, aparently because of the Visual Studio extension
**To Reproduce**
1. Standard installation

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)
[log1.txt](https://github.com/stride3d/stride/files/4521635/log1.txt)

**Additional context**

**Comment by Eideren** [comment] 2020-04-23 09:50
Duplicate of #653

**Closed** 2020-04-27 17:55 UTC
Labels: bug
