### ISSUE TITLE
Android project can not be created

### ISSUE THREAD

**Issue by Agredo** [stride3d/stride#1001] opened 2021-01-22 22:56 UTC
A Android project can not be created with the current beta version (5.0.1.1381)

Failed to load asset! Reason: The file "Resource.Designer.cs" can not be found.

![image](https://user-images.githubusercontent.com/16531090/105557805-69727980-5d0d-11eb-9216-8f58eb034938.png)

**Comment by Eideren** [comment] 2021-01-23 10:01
duplicate of https://github.com/stride3d/stride/issues/827#issuecomment-730392218

**Closed by Eideren** 2021-01-23 10:01 UTC
