### ISSUE TITLE
Game sometimes fail to build with Error while deserializing node 

### ISSUE THREAD

**Issue by jayrulez** [stride3d/stride#131] opened 2018-08-22 18:52 UTC
Here is the output:

```
[(0,0)]: Info: Assembly [TurnBasedBattleSim.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] has already been processed, skip it.
[(0,0)]: Info: TurnBasedBattleSim.Game -> C:\Users\Robert Campbell\Desktop\GameDev\Xenko\TurnBasedBattleSim\TurnBasedBattleSim\TurnBasedBattleSim.Game\bin\Debug\net461\TurnBasedBattleSim.Game.dll
[(0,0)]: Info: Assembly [TurnBasedBattleSim.Windows, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] has already been processed, skip it.
[(0,0)]: Info: TurnBasedBattleSim.Windows -> C:\Users\Robert Campbell\Desktop\GameDev\Xenko\TurnBasedBattleSim\TurnBasedBattleSim\Bin\Windows\Debug\TurnBasedBattleSim.Windows.exe
Info: BuildEngine arguments: --disable-auto-compile --project-configuration Debug --platform=Windows --profile=Windows --project-configuration=Debug --output-path=C:\Users\Robert Campbell\Desktop\GameDev\Xenko\TurnBasedBattleSim\TurnBasedBattleSim\Bin\Windows\Debug\data --build-path=C:\Users\Robert Campbell\Desktop\GameDev\Xenko\TurnBasedBattleSim\TurnBasedBattleSim\TurnBasedBattleSim.Windows\..\Cache\data --package-file=C:\Users\Robert Campbell\Desktop\GameDev\Xenko\TurnBasedBattleSim\TurnBasedBattleSim\TurnBasedBattleSim.Windows\..\TurnBasedBattleSim.xkpkg --log-pipe=net.pipe://localhost/Xenko.Core.Assets.Editor.a541c095-b6f2-4534-a446-45ba674b2394 --verbose
Info: Starting builder.
BattleCard(0,0): Warning: Ignored dictionary item that could not be deserialized
BattleCard(0,0): Warning: Ignored member [Entity.Components] that could not be deserialized:
(Lin: 28, Col: 20, Chr: 1265) - (Lin: 28, Col: 20, Chr: 1265): Error while deserializing node [Mapping start [anchor = , tag = , isImplicit = True, style = Normal]]:
Object reference not set to an instance of an object.
C:/Users/Robert Campbell/Desktop/GameDev/Xenko/TurnBasedBattleSim/TurnBasedBattleSim/Assets/Shared/BattleCard.xkprefab(0,0): Error: Failed to load asset from path [C:/Users/Robert Campbell/Desktop/GameDev/Xenko/TurnBasedBattleSim/TurnBasedBattleSim/Assets/Shared/BattleCard.xkprefab]. Reason: The path [(object).Hierarchy.Parts[7af3f79c-b2a9-4503-bef9-01e22cec3afb].Entity.Components{a580c287da86a24485c35d7c8fb90298}.Children{a9274685b3b775935392edb57f692cf2}] contains a non-valid item id on a collection.. The path [(object).Hierarchy.Parts[7af3f79c-b2a9-4503-bef9-01e22cec3afb].Entity.Components{a580c287da86a24485c35d7c8fb90298}.Children{a9274685b3b775935392edb57f692cf2}] contains a non-valid item id on a collection.
BattleCard(0,0): Warning: Asset [6b7ef058-03b7-4ee9-b74e-e719ca86329f:BattleCard] not found. Required for package [TurnBasedBattleSim]
[(0,0)]: Info: RunTime 00:00:02.29
[C:\Users\Robert Campbell\.nuget\packages\xenko\3.0.0.3\Targets\Xenko.targets(374,5)]: Error: The command ""C:\Users\Robert Campbell\.nuget\packages\xenko\3.0.0.3\Bin\Windows\Xenko.Core.Assets.CompilerClient.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows --profile=Windows --project-configuration=Debug --output-path="C:\Users\Robert Campbell\Desktop\GameDev\Xenko\TurnBasedBattleSim\TurnBasedBattleSim\Bin\Windows\Debug\data" --build-path="C:\Users\Robert Campbell\Desktop\GameDev\Xenko\TurnBasedBattleSim\TurnBasedBattleSim\TurnBasedBattleSim.Windows\..\Cache\data" --package-file="C:\Users\Robert Campbell\Desktop\GameDev\Xenko\TurnBasedBattleSim\TurnBasedBattleSim\TurnBasedBattleSim.Windows\..\TurnBasedBattleSim.xkpkg" --log-pipe="net.pipe://localhost/Xenko.Core.Assets.Editor.a541c095-b6f2-4534-a446-45ba674b2394" --verbose" exited with code 1.
```

Not too sure what this is about as the game sometimes build but most times doesn't.

**Comment by xen2** [comment] 2018-08-23 00:29
Could you share with us the `BattleCard.xkprefab` file please?

**Comment by jayrulez** [comment] 2018-08-24 20:11
This was caused by a property on a script attached to an entity in the prefab.

```
public static readonly RoutedEvent<RoutedEventArgs> ClickEvent = EventManager.RegisterRoutedEvent<RoutedEventArgs>("Click", RoutingStrategy.Bubble, typeof(Canvas));
```

**Comment by fluffapparition** [comment] 2018-11-29 22:46
> I just had the same issue right after doing something in my playground scene (I call it that because it's only purpose is for testing new content while it's being made, especially since I just started this project less than a couple months ago.)
> ////////////////////////////////////////////////
> Here's the scene file if you wanna look at it:
> https://drive.google.com/open?id=1S7MvBLfOjZi8BoymFESYY5sF9gkt6vJR
> 
> I also heard that adding sprites/billboards (which is exactly what I did right before this happened) causes these issues in certain scenarios, so maybe see what that's all about? @xen2 Yeah, I'm looking right at you now.

Actually, I just saw a pattern in that file: the only two objects causing the error were also the only two objects with SceneObjectResponseInfo. I _DID_ fix all the ruined ScriptComponents in the player entity, but not the other entities, and in the editor after I fixed the missing references, it looked like they disappeared so I had no idea there would be a non-existent version contained in the scene file. I used a text editor to remove the misbehaving components manually, then everything worked again.

If @jayrulez happened to have messed with the Assembly Name setting in the properties for the "(Game Name Here).Game" project like I did, then fix all the broken references caused by that change, it would reset/remove all of those repaired components (Why it does that, I'll never know. Not so convenient in my opinion :v).

But when they are 'removed,' they aren't really, the editor just expects them to be until it finds out there's a supposedly non-existent copy still there in the file, and it has no idea what to do with it because the actual object no longer exists.

This seems like an obvious bug. I'm not saying this is what happened to @jayrulez, since I don't have the right clues to say for sure, but @xen2, this needs some fixing up. I don't see why the objects are deleted, for one thing, it just seems like an inconvenience to me. But if you ARE going to do that, then you need to make it remove them completely so that this doesn't happen.

**Comment by Eideren** [comment] 2020-04-27 21:25
Duplicate of #563 , closing this one off.

**Closed by Eideren** 2020-04-27 21:25 UTC
