### ISSUE TITLE
 Inverse Kinematics (IK) solver

### ISSUE THREAD

**Issue by anan1213095357** [stride3d/stride#1698] opened 2023-06-19 07:41 UTC
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. Currently, our software does not include an Inverse Kinematics (IK) solver, which can limit our capabilities in various animation and robotics applications. The lack of an IK solver may increase the complexity and the time needed to calculate the joint parameters that achieve the desired positions of the robotic manipulator or character.

**Describe the solution you'd like**
I would like to have an integrated Inverse Kinematics solver in our software. This solver should include support for different IK algorithms such as CCD, FABRIK, and Jacobian methods. It would be great if the solver could handle both single and multiple end-effectors and constraints.

**Describe alternatives you've considered**
An alternative could be to integrate an external IK library into our system, but this could lead to problems with compatibility and maintainability. Having a built-in IK solver will provide more flexibility and control over the feature.

**Additional context**
An IK solver is fundamental in various fields like computer animation, game development, robotics, and even biomechanics. It is essential for calculating joint parameters that would put an end-effector in a desired position.

- **What are the usecases?** The IK solver can be used in character animation for game development, robotic arm manipulations, posture prediction in biomechanics, etc.
- **What kind of options/settings are expected/wanted?** Options for different IK algorithms (CCD, FABRIK, Jacobian), single/multiple end-effectors, and constraints.
- **What would the (pseudo) code look like?** Something like this: `ik_solver.solve(end_effector_position, algorithm='CCD')`
- **Is the feature affecting behaviour in the editor?** Yes, it could come with visual representation of the IK chains and a user-friendly interface for parameter adjustment.
  - **if so: how should this look in the editor?** It could show the IK chains and allow users to select and adjust the parameters interactively.
- **Is there a component or datastructure?** Yes, the IK solver could be a new component that uses data structures for the kinematic chain, joints, and end-effectors.
- **what kind of documentation is needed or needs to be updated?** A complete documentation explaining the usage of the new IK solver component and its options, along with updates in the parts where IK solutions are applicable.
- **Should there be an example project?** Yes, an example project showcasing the usage of the IK solver in different scenarios (robotics, animation) would be beneficial.

**Comment by Eideren** [comment] 2023-06-19 14:03
Duplicate of #103

**Closed by Eideren** 2023-06-19 14:03 UTC
Labels: enhancement

**Comment by Doprez** [comment] 2023-06-19 20:56
I dont feel like that issue should close this request. 

I think this one is a much higher level feature request similar to what was attempted [here](https://github.com/flipdp/Stride.IK/tree/master). I dont believe this repo was finished but I havent tried it yet so I am not 100% sure if it works or not.

**Comment by Eideren** [comment] 2023-06-19 21:31
I couldn't say whether it is higher or lower level given how little detail the previous issue contained, this one definitely goes into more detail but the other has more discussion that would be lost if I were to close it, and I didn't see any reason why both issues should coexist given that neither of them are about one specific thing but about IK support in general.
Feel free to let me know if you disagree and I'll open it back up, what would you do with the other issue though, I think it would be better to have just one conversation around this subject.

**Comment by Doprez** [comment] 2023-06-19 22:12
This makes sense and I am now realizing I misunderstood the other issue as being closed but I was seeing the closed tag from this linked story lol. My mistake!
