### ISSUE TITLE
Compilation suddenly fails with "[Package] is already loaded".

### ISSUE THREAD

**Issue by TylerDM** [stride3d/stride#446] opened 2019-05-12 17:04 UTC
**Release Type**: Official Release/GitHub (please choose appropriate option)
Official Release

**Version**: Version number and/or git branch
Xenko Game Studio 3.1.0.1-beta02-0550

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows 10

**Describe the bug**
When attempting to run the game from Xenko or Visual Studio build fails with error:
```
Error:Assets [C:/Users/user/Documents/Xenko Projects/FirstPersonShooter/Assets/EffectCompileLog.xkeffectlog] with location [EffectCompileLog] from Package [C:/Users/user/Documents/Xenko Projects/FirstPersonShooter/FirstPersonShooter.Windows/FirstPersonShooter.Windows.xkpkg] is already loaded from package [C:/Users/user/Documents/Xenko Projects/FirstPersonShooter/FirstPersonShooter.Game/FirstPersonShooter.Game.xkpkg]
[C:\Users\user\.nuget\packages\xenko.core.assets.compilerapp\3.1.0.1-beta02-0550\build\Xenko.Core.Assets.CompilerApp.targets(68,5)]: Error:The command ""C:\Users\user\.nuget\packages\xenko.core.assets.compilerapp\3.1.0.1-beta02-0550\build\..\lib\net472\Xenko.Core.Assets.CompilerApp.exe"  --disable-auto-compile --project-configuration "Debug" --platform=Windows --project-configuration=Debug --property:RuntimeIdentifier=win7-x86 --output-path="C:\Users\user\Documents\Xenko Projects\FirstPersonShooter\Bin\Windows\Debug\data" --build-path="C:\Users\user\Documents\Xenko Projects\FirstPersonShooter\FirstPersonShooter.Windows\obj\xenko\assetbuild\data" --package-file="C:\Users\user\Documents\Xenko Projects\FirstPersonShooter\FirstPersonShooter.Windows\FirstPersonShooter.Windows.csproj" --log-pipe="net.pipe://localhost/Xenko.Core.Assets.Editor.9ef52b60-21f2-460b-a64a-a75da53dc9a7" --verbose" exited with code **1.**
```

**To Reproduce**
Just going back and forth editing code in VS and looking around (but not editing) things in Game Studio.  I was playing with the First Person Shooter sample specifically when it fell apart.

**Expected behavior**
Game should build and then run.

**Log and callstacks**
[log.txt](https://github.com/xenko3d/xenko/files/3170347/log.txt)

**Additional context**
I also tried clean and rebuild.  No change.

**Comment by Eideren** [comment] 2020-04-28 15:57
Duplicate of #301

**Closed by Eideren** 2020-04-28 15:57 UTC
Labels: bug
