### ISSUE TITLE
Terrain feature building process

### ISSUE THREAD

**Issue by howarduong** [stride3d/stride#2425] opened 2024-09-02 05:52 UTC
So when can you start the update of the terrain plate, I see that Godot also has unofficial plugin support. I hope you will pay attention

**Comment by Eideren** [comment] 2024-09-02 06:55
Stride is a community driven game engine, meaning that users working on this engine do it out of their own free time, if you want to see a feature in the engine, your best bet is to do it yourself or find someone who would.
Still, this is a duplicate of #54, closing this one

**Closed by Eideren** 2024-09-02 06:55 UTC
Labels: enhancement
