### ISSUE TITLE
RightShift not detected properly

### ISSUE THREAD

**Issue by CharlesWoodhill** [stride3d/stride#929] opened 2020-12-03 14:00 UTC
**Describe the bug**
No matter which shift key is pressed (right or left) its always LeftShift in stride.

**Expected behavior**
Correct detection.

**Solution**
i think the scancode (36) used in InputSourceWinfroms.cs is wrong
LeftShift = 42, RightShift = 54; 
i got it from debugging, and it corresponds with:
http://www.qb64.org/wiki/Keyboard_scancodes#INP_Scan_Codes

so the change of (scanCode != 36) to (scanCode == 42) should fix it.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/13883399/101026662-7679b480-3577-11eb-9e56-6b3fee7f739b.png)

**Additional context**
Sorry cant fix it myself atm, no time to create fork, have other fork with many other changes.

**Comment by Eideren** [comment] 2020-12-03 16:04
Duplicate of #754

**Closed by Eideren** 2020-12-03 16:04 UTC
Labels: bug
