### ISSUE TITLE
Could not find a compatible version of MSBuild

### ISSUE THREAD

**Issue by Wario-Ametrano** [stride3d/stride#1148] opened 2021-09-16 10:27 UTC
I cannot start Stride, I have installed the latest version of Visual Studio 2019 and the latest version of Stride (4.1.0.1459), I have installed and uninstalled visual studio and stride many times but the error remains.
![Cattura](https://user-images.githubusercontent.com/86927539/133596337-024342ec-ffec-4d8e-bbe4-67c68e1a15ef.PNG)

**Comment by Eideren** [comment] 2021-09-16 10:42
Duplicate of #756

**Closed by Eideren** 2021-09-16 10:42 UTC
Labels: bug

**Comment by Wario-Ametrano** [comment] 2021-09-16 10:44
ok sorry i wasn't sure it was the same problem
