### ISSUE TITLE
Installing Xenko for the first time fails, VS extension issue

### ISSUE THREAD

**Issue by matej-zajacik** [stride3d/stride#412] opened 2019-03-16 22:47 UTC
**Release Type**: http://xenko.com/files/XenkoSetup.exe

**Version**: 3.0.0.8 and 3.1.0.1-beta02-0539

**Platform(s)**: Windows 10

**Describe the bug**
Installing either the 3.0 or 3.1 version fails due to failing to install the VS extension. This is the first time I'm trying out Xenko on this computer.

**To Reproduce**

1. Run Xenko.exe.
1. The launcher says that no version of Xenko is installed. It asks you to install the latest. Confirm.
1. It also asks to install a VS extension. Confirm.
1. It produces an error (see logs.).

**Expected behavior**
No errors, functioning Xenko installation.

**Screenshots**
![image](https://user-images.githubusercontent.com/8986611/54482426-800f3600-4843-11e9-9284-c44b0d225711.png)

**Log and callstacks**
`An error occurred while installing version 3.1.0.1-beta02-0539.
Error code 1 while running install package process [C:\Users\admin.nuget\packages\xenko.gamestudio/3.1.0.1-beta02-0539\tools\packageinstall.exe]
Error: System.InvalidOperationException: Visual Studio 2017 install failed with error 1 at Xenko.PackageInstall.Program.CheckVisualStudioAndBuildTools() in D:\BuildAgent\work\8cafb933a54b01d0\sources\tools\Xenko.PackageInstall\Program.cs:line 102 at Xenko.PackageInstall.Program.Main(String[] args) in D:\BuildAgent\work\8cafb933a54b01d0\sources\tools\Xenko.PackageInstall\Program.cs:line 51
 at Xenko.Core.Packages.NugetStore.RunPackageInstall(String packageInstall, String arguments, ProgressReport progress) at Xenko.Core.Packages.NugetStore.OnPackageInstalled(Object sender, PackageOperationEventArgs args) at Xenko.Core.Packages.NugetStore.<InstallPackage>d50.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xenko.LauncherApp.ViewModels.PackageVersionViewModel.<>cDisplayClass550.<<Download>b_0>d.MoveNext()`

**Comment by matej-zajacik** [comment] 2019-03-16 22:49
A weird thing is that even if I refuse the prompt to install the extension, it attempts to install it anyway.

**Comment by Kryptos-FR** [comment] 2019-03-17 05:47
Installation of Xenko and the VS extension are unrelated.

**Comment by matej-zajacik** [comment] 2019-03-17 06:32
@Kryptos-FR Seems like that is the reason it is failing though.

**Comment by matej-zajacik** [comment] 2019-03-17 06:45
Reinstalling VS, and thus updating the Visual Studio Installer to the latest version, fixed the problem. I managed to install the latest Xenko version now.

**Comment by kiridu1988** [comment] 2019-03-21 14:47
I found a solution to all Xenko problems!

Just use Godot and do not waste time!

**Comment by ryancheung** [comment] 2019-03-22 02:35
> I found a solution to all Xenko problems!
> 
> Just use Godot and do not waste time!

Godot is good, but it's scene-graph-based, and even has no Sprite Batching.
Xenko is just like XNA, and does Sprite Batching like DirectX, which is all better than Godot for my game.

**Comment by kiridu1988** [comment] 2019-03-22 05:30
> 
> 
> > I found a solution to all Xenko problems!
> > Just use Godot and do not waste time!
> 
> Godot is good, but it's scene-graph-based, and even has no Sprite Batching.
> Xenko is just like XNA, and does Sprite Batching like DirectX, which is all better than Godot for my game.

But it runs without problems.

**Comment by ryancheung** [comment] 2019-03-22 06:25
But it’s Scene Graph, if you game is ok, then just use godot.
And in most case this engine shall run without problem, at least I fine.
The point is You can say you got a problem in a framework and say just use another, since you don’t even what the framework’s capabile of.
The same sentence as you said could be a godot user got a problem, then somebody don’t even know godot and say Just use Unity.
This is so absurd.

**Comment by DaveTheGameDev** [comment] 2019-03-22 06:28
> But it runs without problems.
@kiridu1988 

Well would you kindly make a new issue with the problems you are having. Saying Xenko has problems is without any information is kinda hard to figure out what is going on. (must be related to this or why else would you comment on this issue :) )

matej-zajacik  already said they fixed the issue by reinstalling Visual Studio and making sure everything is up to date.

**Comment by ryancheung** [comment] 2019-03-22 06:34
I’m a Patron of Godot, and I have no idea of the meaning that godot is better than other.

**Comment by phr00t** [comment] 2019-04-04 18:06
Can you try using my different Xenko distribution method?

https://github.com/phr00t/xenko/releases/tag/3.1b-R1

Please mention me with results if you try it!

**Comment by abgenullt** [comment] 2020-03-03 07:48
Installing "Development Tools plus .NET Core 2.1" and restart the computer (because windows installer doesn't close properly) fixed it for me.

**Comment by Eideren** [comment] 2020-04-28 16:10
Duplicate of #653

**Closed by Eideren** 2020-04-28 16:10 UTC
Labels: bug
