### ISSUE TITLE
[Material] Tessellation displacement doesn't work with normal map

### ISSUE THREAD

**Issue by MetaCitizenOffical** [stride3d/stride#617] opened 2020-02-27 00:41 UTC
**Release** Type: Game Studio Official Release

**Version:** 3.1.01

**Platform(s):** Windows

**Describe the bug**
Flat Tessellation only works in Displacement mode Shader Stage Vertex
Point Normal Tessellation doesn't work at all.

It appears that with Flat Tessellation in Shader Stage Vertex mode it displaces the meshes vertices before tessellating. Which defeats the purpose of tessellation.

Im also wondering if there is a setting somewhere to change when the distance based tessellations starts/blends.

**Screenshots**
Xenko Flat Tesselation
![Xenko Flat Tesselation](https://user-images.githubusercontent.com/25397545/75401062-3dad0080-58be-11ea-83d0-dcd943c4c060.png)

Xenko Flat Tesselation Shader Stage Vertex
![Xenko Flat Tesselation Shader Stage Vertex](https://user-images.githubusercontent.com/25397545/75401234-bc09a280-58be-11ea-8c61-cf84c93d014e.png)

Xenko Point Normal Tesselation
![Xenko Point Normal Tesselation](https://user-images.githubusercontent.com/25397545/75401070-4271b480-58be-11ea-86eb-aa903d0b47d5.png)

Shader Stage
![Shader Stage](https://user-images.githubusercontent.com/25397545/75401240-bf9d2980-58be-11ea-872e-c5cccf978b52.png)

**Comment by JannekP** [comment] 2020-02-28 21:45
@MetaCitizenOffical To use apply displacement to the tesselation you should use the domain Shader stage.
The displacement itself does work, but it doesn't work with a normal map, but it is needed to have one. (Which seems like a bug to me)

Please try, if it works, with disabled normal map

**Comment by MetaCitizenOffical** [comment] 2020-02-28 22:13
Disabling the normal map is the solution! Thank you :)

**Comment by Eideren** [comment] 2020-04-28 19:35
Duplicate of #477

**Closed by Eideren** 2020-04-28 19:35 UTC
Labels: bug
