### ISSUE TITLE
[Editor] The Editor is throwing GetAndroidPackage do no exist in the project when trying to build an Adroid project

### ISSUE THREAD

**Issue by xwellingtonx** [stride3d/stride#658] opened 2020-04-20 18:37 UTC
**Release Type**: 
GitHub

**Version**: 
master

**Platform(s)**: 
Android

**Describe the bug**
When trying to build an Android project through the Editor, it's throwing the error message
"Error:The path "GetAndroidPackage" do not exist in the project."

**To Reproduce**
1. Create a project with Android added
2. Select the Android project as the current project
2. Start an Android emulator or Device
3. Build the project 

**Expected behavior**
The build process should be complete without an issue like in Visual Studio.

**Screenshots**
![image](https://user-images.githubusercontent.com/10274446/79786861-faab5e80-833d-11ea-8a38-46e6008c37e4.png)

**Additional context**
#657

**Comment by Basewq** [comment] 2020-04-21 02:47
No idea how to fix this, however it seems to be related to commit 90ce1a0f9c8605ade31504cb7c76eb3905ff1eaf where the file `Targets/Xenko.Android.targets` was removed.
It has the line:
```
  <!-- Target to get signed .apk name -->
  <Target Name="GetAndroidPackage" DependsOnTargets="_ValidateAndroidPackageProperties" Returns="$(_AndroidPackage)"/>
```

**Comment by xwellingtonx** [comment] 2020-04-21 08:49
@Basewq If we check the way that VS is calling the build for Android we might discover how to fix it because there is working fine even without this file.

**Comment by Basewq** [comment] 2020-04-21 08:55
Possibly, though this stuff is out of my depth.
Also, here's the line where the Editor's making the build, calling that target:
https://github.com/stride3d/stride/blob/273dfddd462fd3746569f833e1493700c070b14d/sources/editor/Stride.GameStudio/DebuggingViewModel.cs#L428

**Comment by xwellingtonx** [comment] 2020-04-21 09:03
@Basewq Yeah, it's out of my knowledge too.

@xen2 Any thoughts about it?

**Comment by Eideren** [comment] 2020-04-28 10:00
Duplicate of #206

**Closed by Eideren** 2020-04-28 10:00 UTC
Labels: bug
