### ISSUE TITLE
The Solution Explorer in the Stride Editor won't show the directory structure properly

### ISSUE THREAD

**Issue by ioannis-koukourakis** [stride3d/stride#1193] opened 2021-11-20 15:28 UTC
**Release Type**: GitHub master-4.0
**Version**: 4.0
**Platform(s)**: Windows 10/11

**Describe the bug**
It seems like the Stride Editor Solution Explorer is skipping certain directory folders and shows up script under the Code dir instead. Example:

I made a structure manually in the Stride editor solution explorer that goes like:
Solution MyGame->MyGame.Game->Code->Entities->Characters->Player->Some Script Here.
If I restart the editor what I see is:
Solution MyGame->MyGame.Game->Code->Player->Some Script Here.

Repeating the same process often ends up skipping different folders. 

Although I can't be certain, I think it's related to having folders containing other folders only while no assets are directly contained in them. 
The screenshots below highlight the differences between the VS Studio folder structure and what the Stride Editor is displaying. 

Good to note that I compiled the engine from source (master-4.0).

**To Reproduce**
I was able to reproduce quite a few times by repeating the following process.
1. In the solution explorer in the Stride editor create a folder inside the "Code" directory and name it "Entities".
2. Repeat the above process and make another folder inside the "Entities" folder and call it "Characters".
3. Inside the "Characters" folder create another folder and call it "Player".
4. Last but not least create a new script inside the "Player" folder.
5. Save the project.
6. Close the editor and start it again. The folders you created should be messed up now. 

Good to note that VS studio maintains the project structure just fine. 

**Expected behavior**
The Stride editor should display the Project structure as really is and not skip folders. 

**Screenshots**
Stride's Solution Explorer displayed structure.
![StrideStructure](https://user-images.githubusercontent.com/11280777/142731069-4ebc845b-46b4-41a1-b902-97a72c5e1246.jpg)
VS Studio proper structure
![VSStructure](https://user-images.githubusercontent.com/11280777/142731059-46be4ab1-11c7-4168-9e09-2d52042899a3.jpg)

**Comment by manio143** [comment] 2021-11-23 05:43
Can you check if this is the same issue I fixed in #848 or is it more severe?

**Comment by Aggror** [comment] 2021-11-23 15:02
One of the first things I noticed when working with Stride a couple years ago, was that empty newly created empty folder in windows explorer are not shown in the view.
 When I asked around I was told that this was by design and that in the editor, those empty folders are automatically collapsed or not shown depending if the have nest folders/files.

**Comment by Eideren** [comment] 2021-11-23 15:34
Yes, this is most likely resolved by #848 given that he is running on master-4.0 instead of latest. Is there a particular reason why you're not running on latest @ioannis-koukourakis ?

**Comment by ioannis-koukourakis** [comment] 2021-11-24 18:00
I currently use 4.0 since it's marked as stable release @Eideren! I'll switch to the latest one and I guess this report can be marked as fixed then :) Cheers!

**Closed** 2021-11-25 04:09 UTC
Labels: bug
