### ISSUE TITLE
Web Browser Platform support

### ISSUE THREAD

**Issue by Ksengine** [stride3d/stride#677] opened 2020-04-29 05:07 UTC
Add Webbrowser support.
Like **WebGL** or Flash(or both)
**WebGL** is better

This is an open source Javascript/**WebGL** 3D Library, [Copperlicht](https://www.ambiera.com/copperlicht/)
[Download](https://www.ambiera.com/copperlicht/download.html) it here

**Comment by Kryptos-FR** [comment] 2020-04-29 05:19
I'm closing this because:

1. it doesn't follow issue template
2. it has a link that suspiciously looks like spam
3. poster account was created a few days ago
4. that link points to a JavaScript library while Stride is a C# engine, so it is off-topic

In any case, it would be a duplicate of #70.

**Closed by Kryptos-FR** 2020-04-29 05:19 UTC
Labels: enhancement
