### ISSUE TITLE
Missing cleanup on uninstall

### ISSUE THREAD

**Issue by Hammerstad** [stride3d/stride#108] opened 2018-08-14 08:17 UTC
After uninstalling Xenko, my development environment was left in some form of limbo. I had to manually clean the following things in order for everything to work properly:

 - Remove the Xenko extension from visual studio.
 - Remove xenko and xenko-dev feed from global nuget.config.

Please add these steps to your uninstall procedure.

**Comment by Eideren** [comment] 2020-04-28 09:42
Duplicate of #215

**Closed by Eideren** 2020-04-28 09:42 UTC
