### ISSUE TITLE
[Gamestudio] Throwing properties prevent components from being added

### ISSUE THREAD

**Issue by scottyboy805** [stride3d/stride#563] opened 2019-12-06 18:40 UTC
**Release Type:** Official Release
**Version:** 3.1.0.1
**Platform:** Windows 10

**Describe the bug:**

Creating a script with the code below causes all scripts to be removed from entities in Game Studio and makes it impossible to add any scripts to Entites. More information on the forum post [here](https://forums.xenko.com/t/cannot-add-a-script-to-any-entity-in-game-studio/2062).

**Steps to reproduce:**

1. Create a new blank project
2. Create a new SyncScript and name it 'AnimatedSprite' (The name is important for some reason, maybe because it has the word 'Sprite' in it?)
3. Add the following code to the script:

public class AnimatedSprite : SyncScript
    {
        // Declared public member fields and properties will show in the game studio
        SpriteComponent sprite = null;
        public bool Visible
        {
            get { return sprite.Enabled; }
            set { sprite.Enabled = value; }
        }

        public override void Start()
        {
            // Initialization of the script.
        }

        public override void Update()
        {
            // Do stuff every new frame
        }
    }

**Expected behaviour:**
Should be able to add the script to an entity in Game Studio.

**Actual Behaviour:**
Adding the script from the property grid window will not work and trying to save the project immediatley after will generate an error.
Adding the script by dragging to the property grid will crash Game Studio.

**Comment by dfkeenan** [comment] 2019-12-06 23:43
In the forum post you say commenting out the `Visible` property "fixes" the problem. My guess is that it is throwing a `NullReferenceException` from the `Visible` property because the `sprite` field is null. Perhaps put some null checks in there.

**Comment by scottyboy805** [comment] 2019-12-07 08:45
Yes I suspect that is what is happening and I will test it later to confirm but surely it should be handled correctly by Xenko. Adding that bit of code caused all scripts to be removed from scene entities and prefabs and made it impossible to re-add them. If there is a problem displaying a property I would expect an error to be logged, the property to be skipped or maybe even displayed with the actual exception that occurred kind of like VS debugger when accessing a member that throws an exception.

**Comment by Eideren** [comment] 2020-04-27 21:57
Duplicate of #209

**Closed by Eideren** 2020-04-27 21:57 UTC
Labels: help wanted
