### ISSUE TITLE
Broken Templates (TopDown RPG, First Person Shooter)

### ISSUE THREAD

**Issue by ToolmakerSteve** [stride3d/stride#1181] opened 2021-11-06 21:36 UTC
**Release Type**: GitHub

**Version**: master - 2bf586d6

**Platform(s)**: Windows

**Describe the bug**
When first launch (empty) game:
E1203: The type [ComputeColorConstantColorLink] has generic parameters defined but only 0/1 arguments were passed when creating its instance"

**To Reproduce**
1. Update master branch to 2bf586d6.
2. Build GameStudio in Stride.sln. (VS Enterprise 2019, up-to-date.)
3. Run Stride.GameStudio project.
4. Select a template. Two of these (TopDown RPG, First Person Shooter) will give this symptom in step (5). Others are good.
5. F5 (Build project and start the game.)

RESULT: Error messages in Output pane. Game does not start.

**Expected behavior**
Game screen appear, without error messages in GameStudio.

**Log and callstacks**
[TopDownRPG Build Output.txt](https://github.com/stride3d/stride/files/7491280/TopDownRPG.Build.Output.txt)

First error is on line 1556:

    [EXEC(0,0)]: Error: [C:/Users/toolm/.nuget/packages/stride.rendering/4.1.0.1-beta/stride/Assets/Materials/ComputeColors/Shaders/ComputeColorConstantColorLink.sdsl(9,1)]  E1203: The type [ComputeColorConstantColorLink] has generic parameters defined but only 0/1 arguments were passed when creating its instance

**Additional context**

**Comment by Eideren** [comment] 2022-01-03 17:38
Followed the instructions on latest and couldn't reproduce the issue, feel free to re-open or create a new issue if this hasn't been fixed on your end.

**Closed by Eideren** 2022-01-03 17:38 UTC
Labels: bug, area-Samples
