### ISSUE TITLE
StrideCompilerServices doesnt resolve

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [stride3d/stride#2073] opened 2023-12-05 08:27 UTC
**Release Type**: 
Current git state
**Version**: 
4.2

**Platform(s)**: Does the problem occur on Windows, Android...?

**Describe the bug**
No project can resolve the CompilerServices even though every project should
![grafik](https://github.com/stride3d/stride/assets/107197024/bcfb4683-b4aa-4a80-aeda-bea638f9036d)

**To Reproduce**
1. get latest stride
2. check analysetools if stride compilerservices is there
3. its not there

**Expected behavior**
every project should have it as analyse tool and it should show the rolsyn diagnostics

**Comment by archanox** [comment] 2023-12-05 10:38
Ah, I was encountering this issue on Windows on Arm too, I thought it was a me problem. Does this need to be bisected?

**Comment by IXLLEGACYIXL** [comment] 2023-12-05 10:43
> bisected

i have amd 64 bit, sooo its on all machines

**Comment by IXLLEGACYIXL** [comment] 2023-12-30 15:10
could it be that central package management is causing this?

**Comment by Kryptos-FR** [comment] 2023-12-30 20:24
> could it be that central package management is causing this?

I don't think that's the cause, or at least not only.

I just checked out commit 1fc04d4d0ef6fd31921dbcdec07d1c7050934714 (which is where central package management was first merged) and I can see the analysers, though I can't see the rules. I will try to bisect.

**Closed** 2024-01-11 06:43 UTC
Labels: bug
