### ISSUE TITLE
[Vulkan] Problem running project In Vulkan API (WriteDiscard)

### ISSUE THREAD

**Issue by blueangel74** [stride3d/stride#602] opened 2020-02-11 09:36 UTC
Hi,I'm trying to compile a project in Vulkan, I inserted the <RuntimeIdentifier> win-vulkan </RuntimeIdentifier> line in the .proj file. (Is this the procedure?) The compilation is successful but at the time of launching the executable I get this error / exception: System.InvalidOperationException: 'Can't use WriteDiscard on Graphics API that doesn't support renaming'.I tried with the vers. 3.1.0.1 and 3.2.0.1 beta2. Any ideas? Thanks
P.S. I tried the same procedure on the First person character template and it worked well, without error/exception.

![Exception](https://user-images.githubusercontent.com/11281315/74225087-56ac9380-4cba-11ea-9bfc-a702ba437eda.PNG)

**Comment by blueangel74** [comment] 2020-02-11 11:59
Ok, after several tests the transition to Vulkan works on vers. 3.2.0.1 beta 2 for new projects and for those updated from the previous version 3.1.0.1, while the problem remains on vers. 3.1.0.1, I also tried creating new projects and templates, but the error / exception remains.

**Comment by blueangel74** [comment] 2020-02-11 21:36
A correction following other tests unfortunately not even in 3.2.0.1 I managed to activate Vulkan as mentioned above, in effect by adding the change to the .proj. Vs creates the binaries in Vulkan, but in fact always uses Directx as you can see from the screenshot below.
![ProjectXenko_3 2 0 1beta2_Vulkan_set](https://user-images.githubusercontent.com/11281315/74281590-00257080-4d1f-11ea-835b-9c915f4cea97.PNG)

**Comment by blueangel74** [comment] 2020-02-11 22:55
Solved !! I created a new Xenko 3.1.0.1 project, without making changes, changed the proj file. and here is vulkan, so simple. There was perhaps incompatibility with an existing directx build in the other projects in bin folder, although vulkan had his own folder, but maybe he didn't like it.

**Comment by blueangel74** [comment] 2020-02-11 23:20
Unfortunately with the same procedure, new project without modifications and with the modification of the .proj_ file in the version of Xenko 3.2.0.1beta2 does not detect Vulkan! Maybe some changes have been made!
![Test_NewProject_Xenko_vers_3 2 0 1_beta2Vulkan](https://user-images.githubusercontent.com/11281315/74288751-7c26b500-4d2d-11ea-9af2-b1167f583d6c.PNG)

**Comment by blueangel74** [comment] 2020-02-12 09:09
Ok, checking the Nuget Xenko.graphics packages in this case in the 3.2.0.1 version several folders are missing compared to the official version 3.1.0.1, in fact at runtime there is only the "win" Screen folder below.
![Catt](https://user-images.githubusercontent.com/11281315/74319738-b91b9780-4d7f-11ea-8065-f0006106708b.PNG)
![C](https://user-images.githubusercontent.com/11281315/74319760-c042a580-4d7f-11ea-92d6-fb186cca61af.PNG)

**Comment by Eideren** [comment] 2020-04-27 18:39
Duplicate of #630

**Closed by Eideren** 2020-04-27 18:39 UTC
Labels: bug
