### ISSUE TITLE
Engine fails at runtime when targetting .NET Core 3.1

### ISSUE THREAD

**Issue by thargy** [stride3d/stride#936] opened 2020-12-06 17:24 UTC
**Release Type**: Official Release

**Version**: 4.0.0.1-beta04-1317

**Platform(s)**: Windows

**Describe the bug**
The following exception is thrown when running a project targeting netcoreapp3.1.

```Could not load native library freetype.dll from path [C:\Source\Xenko.CustomRootRenderFeature\CustomRootRenderFeature\Bin\Windows\Debug\x64\freetype.dll] using CPU architecture x64.```

**To Reproduce**
Target netcoreapp3.1.

**Comment by thargy** [comment] 2020-12-06 18:12
On further investigation, the `freetype.dll` is missing entirely from `Bin\Windows\Debug\x64` when targeting .NET Core 3.1.

Manually copying the dll to that folder (from `C:\Users\<USER>\.nuget\packages\stride.graphics\4.0.0.1-beta04-1317\runtimes\win\lib\netstandard2.0\Direct3D11\x64`) resolves the problem and allows the code to run, suggesting that the issue is related to a problem with the MSBuild configuration when targeting that framework.

**Comment by Zeroto** [comment] 2020-12-06 18:34
This is a duplicate of #837 

You need to add a RuntimeIdentifier to identity the platform it will run on

**Closed** 2020-12-06 18:42 UTC
Labels: bug
