### ISSUE TITLE
First time installing, create new project than editor not responding at all?

### ISSUE THREAD

**Issue by DwiYI** [stride3d/stride#292] opened 2018-12-12 00:58 UTC
Release Type:
Official Release

Version:
3.0.0.6

Platform(s):
Windows 10

Spec Pc : 
cpu : ryzen 1700 
gpu : rx 480

Describe the bug
click everywhere in editor after that not responding 

To Reproduce : 
only click on editor

Screenshoot : 
![xenko](https://user-images.githubusercontent.com/19425248/49839878-8a083f80-fde3-11e8-9212-cbb6fa0f4a2f.png)

**Comment by Kryptos-FR** [comment] 2018-12-12 02:30
How often did you reproduce the issue? Was it once or everytime your start the GameStudio?

Did you try to start it after closing all other applications? I can see a lot of chrome tab opened at the same time which can take CPU/Memory.

**Comment by DwiYI** [comment] 2018-12-12 03:20
hai @Kryptos-FR, 

my cpu utilization : only 2 % used
and memory still have : 4 gb left.

i have tried uninstall-installed xenko 2 times and the result same

**Comment by Kryptos-FR** [comment] 2018-12-12 04:16
> How often did you reproduce the issue? Was it once or everytime your start the GameStudio?

I meant opening the editor several times. Not necessarily reinstalling it.

> but one click make app not responding again

Click on the game view, asset view, on the menu? Or the click position doesn't matter?
Also are you using any special pointer device, or is it a classic mouse? 

Finally, could you also try installing Xenko 2.1 (or any other previous versions) and tell us if the same problem occurs? You can install several versions side-by-side from the launcher.

**Comment by Kryptos-FR** [comment] 2018-12-12 05:44
@xen2 This looks like an old issue we had with some version of MSBuild locator, but I thought it had been fixed.

**Comment by DwiYI** [comment] 2018-12-13 21:13
@Kryptos-FR I tried build from source version 3.1.0.1-dev and i can create new game again.

the GameStudio is responding but very slow (waiting **30** seconds selecting asset in MainScene).

cpu usage: 2 -10 % 
mem : 4gb left
disk : 0 %

Is that my computer problem?

PS : sorry my english is bad

**Comment by DwiYI** [comment] 2018-12-14 02:14
Hi @Kryptos-FR updating windows 10 version 1607 to 1809 fix the issue.

i dont know.
is that requirement or my version(1607) is broken ?

thanks

**Comment by Kryptos-FR** [comment] 2018-12-14 03:32
Well, I can't say for sure. Keeping an old version of Windows is not recommended, although in your case that version is still supported.

Does the fact that you didn't upgrade before also means that you never applied the quality updates that are added from time to time (at least once a month)?

The root issue could also be unrelated to the Windows version, but the upgrade process might have cleaned up or fixed up some stuff.

**Comment by DwiYI** [comment] 2018-12-14 04:20
yes, i've disabled windows auto update because it's very annoying (my internet speed is not very fast and eating the speed).

i m upgrade now because i want to check gpu usage  in task manager when xenko is running. My system doesnt have onboard graphic maybe its not using dedicated gpu at all.

**Comment by Eideren** [comment] 2020-04-28 10:20
Main issue resolved through changing to a more recent version. If you still have performance issue open a new issue specifically for it along with other infos about the hardware you are running xenko/stride on, the project files or a small prepro and anything else that you deem useful, thanks !

**Closed by Eideren** 2020-04-28 10:20 UTC
Labels: area-GameStudio, bug
