### ISSUE TITLE
Editor issues when running multiple instances on dual multiple displays.

### ISSUE THREAD

**Issue by jayrulez** [stride3d/stride#116] opened 2018-08-17 00:32 UTC
When I try to run 2 instances of the editor on 2 screens, it seems that the two instances cannot have different sizes
because I can't get the second instance to fullscreen properly on the second monitor
It expands to the first monitor
when I hit the maximize button.

Here is a recording of the issue:
https://drive.google.com/file/d/1V_L2UOJTE-9-6Twmb91GRfsKDXl6Y8N_/view?usp=sharing

**Comment by Kryptos-FR** [comment] 2018-08-17 00:39
I don't think we support properly running multiple instances. Some settings are global and they might get overwritten in that case. That's something we could at least detect (so that only one editor saves those settings) and potentially improve (per-project settings?).

One thing fore sure though is that we can't support opening the same project on multiple instance.

**Comment by xen2** [comment] 2018-08-17 01:38
@Kryptos-FR I think lot of big software simply overwrite with latest settings when opened multiple times. Not ideal of course, but I don't think it is unexpected for most users if it behaves like this for now.
I have often used Game Studio with multiple instances and usually there is no problem.

@jayrulez What are those screen resolutions and display scaling settings? (note that in Windows 10, display scaling settings is per screen).

**Comment by Kryptos-FR** [comment] 2018-08-17 01:43
@xen2 We save the windows position and size in the settings so if you have multiple instances, one will always overwrite the window position of the other, leading to the issue here described.

One thing we could od here is have that particular setting read-only in case multiple instances are opened.

**Comment by xen2** [comment] 2018-08-17 01:52
@Kryptos-FR Yes sure, but in this case it is maximizing a window that fails, this shouldn't read anything from config since it just uses current screen info, right? Or did I misunderstood something?

**Comment by Kryptos-FR** [comment] 2018-08-17 03:42
Yeah there might also be some issues when two monitors with different size especially if one has high DPI and the other not. Windows returns some weird values when querying for the actual screen size.

@jayrulez can you check if you have the same behavior with:
* only one instance but two windows (open the debug window from the debug menu for instance)
* two instances
* make your other monitor the default one and try again both points

**Comment by Eideren** [comment] 2020-04-27 20:54
*He never got back home*
Anyway, I tried to reproduce this issue by following @jayrulez setup but couldn't replicate it.
We need more info before debugging this whole thing but seeing as he didn't find his way back I'll just close this one off. 
Send me a DM and I'll re-open it or create a new one instead if you would rather do that.

**Closed by Eideren** 2020-04-27 20:54 UTC
