### ISSUE TITLE
Finicky sticky movement/strafing in Editor

### ISSUE THREAD

**Issue by jusvit** [stride3d/stride#1857] opened 2023-09-28 09:17 UTC
**Release Type**: Official Release
**Version**: 4.1.0.1898

**Platform(s)**: Windows

**Describe**

I have an annoyance issues after migrating from Unity with regards of moving in the editor.

When flying around in the editor pressing/releasing shift with WASD to strafe and what not, it randomly decides not to move in one direction unless I tap/release the button.

You can see the issue in the video, at random points, the keys get "Stuck", the editor window is still focused and nothing other than WASD and Shift are being pressed (With right click held down the entire time)

https://github.com/stride3d/stride/assets/4002351/5ebd6e31-31fd-4d92-9904-c06655ca87ee

**Comment by Eideren** [comment] 2023-09-28 09:23
Duplicate of #94

**Closed by Eideren** 2023-09-28 09:23 UTC
Labels: bug
